#!/bin/bash

export NUMTHE=750
export NUMRHO=512
#DOMAIN SIZE
export NUMX=512
export NUMY=512
#DOMAIN INFORMATION
export XSTART=-256
export YSTART=-256
export PIXSIZE=1
export RHOSTART=-256
export RAYLENGTH=1024
#SOLVER DATA
export NUMITER=50
#TILE SIZE (MUST BE POWER OF TWO)
export SPATSIZE=256
export SPECSIZE=256
#INDEXING
export SPATINDEXING=5
export SPECINDEXING=5
# 1: CARTESIAN, NATURAL
# 2: CARTESIAN, TRANSPOSED
# 3: MORTON, NATURAL
# 4: MORTON, TRANSPOSED
# 5: HILBERT
export PROJBLOCK=512
export BACKBLOCK=512
export PROJBUFF=48 #KB
export BACKBUFF=48 #KB

export OMP_NUM_THREADS=16
aprun -n 4 -N 1 -cc depth -d $OMP_NUM_THREADS -j 2 ./ptycho
